# Generated by Django 4.0.4 on 2022-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authenticationpost_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationpost',
            options={'managed': False, 'ordering': ('-update_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-update_at',)},
        ),
    ]
